export enum Continent {
  EUROPE = "Europe",
  ANTARCTICA = "Antarctica",
  N_AMERICA = "North America",
  S_AMERICA = "South America",
  AFRICA = "Africa",
  ASIA = "Asia",
  OCEANIA = "Oceania",
}

export const countries = [
  { continent: Continent.ASIA, name: "Afghanistan", code: "AF" },
  { continent: Continent.EUROPE, name: "Albania", code: "AL" },
  { continent: Continent.ANTARCTICA, name: "Antarctica", code: "AQ" },
  { continent: Continent.AFRICA, name: "Algeria", code: "DZ" },
  { continent: Continent.OCEANIA, name: "American Samoa", code: "AS" },
  { continent: Continent.EUROPE, name: "Andorra", code: "AD" },
  { continent: Continent.AFRICA, name: "Angola", code: "AO" },
  {
    continent: Continent.N_AMERICA,
    name: "Antigua and Barbuda",
    code: "AG",
  },
  { continent: Continent.EUROPE, name: "Azerbaijan", code: "AZ" },
  // { continent: Continent.ASIA, name: "Azerbaijan", code: "AZ" },
  { continent: Continent.S_AMERICA, name: "Argentina", code: "AR" },
  { continent: Continent.OCEANIA, name: "Australia", code: "AU" },
  { continent: Continent.EUROPE, name: "Austria", code: "AT" },
  { continent: Continent.N_AMERICA, name: "Bahamas the", code: "BS" },
  { continent: Continent.ASIA, name: "Bahrain", code: "BH" },
  { continent: Continent.ASIA, name: "Bangladesh", code: "BD" },
  { continent: Continent.EUROPE, name: "Armenia", code: "AM" },
  // { continent: Continent.ASIA, name: "Armenia", code: "AM" },
  { continent: Continent.N_AMERICA, name: "Barbados", code: "BB" },
  { continent: Continent.EUROPE, name: "Belgium", code: "BE" },
  { continent: Continent.N_AMERICA, name: "Bermuda", code: "BM" },
  { continent: Continent.ASIA, name: "Bhutan", code: "BT" },
  { continent: Continent.S_AMERICA, name: "Bolivia", code: "BO" },
  {
    continent: Continent.EUROPE,
    name: "Bosnia and Herzegovina",
    code: "BA",
  },
  { continent: Continent.AFRICA, name: "Botswana", code: "BW" },
  {
    continent: Continent.ANTARCTICA,
    name: "Bouvet Island (Bouvetoya)",
    code: "BV",
  },
  { continent: Continent.S_AMERICA, name: "Brazil", code: "BR" },
  { continent: Continent.N_AMERICA, name: "Belize", code: "BZ" },
  {
    continent: Continent.ASIA,
    name: "British Indian Ocean Territory (Chagos Archipelago)",
    code: "IO",
  },
  { continent: Continent.OCEANIA, name: "Solomon Islands", code: "SB" },
  {
    continent: Continent.N_AMERICA,
    name: "British Virgin Islands",
    code: "VG",
  },
  { continent: Continent.ASIA, name: "Brunei Darussalam", code: "BN" },
  { continent: Continent.EUROPE, name: "Bulgaria", code: "BG" },
  { continent: Continent.ASIA, name: "Myanmar", code: "MM" },
  { continent: Continent.AFRICA, name: "Burundi", code: "BI" },
  { continent: Continent.EUROPE, name: "Belarus", code: "BY" },
  { continent: Continent.ASIA, name: "Cambodia", code: "KH" },
  { continent: Continent.AFRICA, name: "Cameroon", code: "CM" },
  { continent: Continent.N_AMERICA, name: "Canada", code: "CA" },
  { continent: Continent.AFRICA, name: "Cape Verde", code: "CV" },
  { continent: Continent.N_AMERICA, name: "Cayman Islands", code: "KY" },
  {
    continent: Continent.AFRICA,
    name: "Central African Republic",
    code: "CF",
  },
  { continent: Continent.ASIA, name: "Sri Lanka", code: "LK" },
  { continent: Continent.AFRICA, name: "Chad", code: "TD" },
  { continent: Continent.S_AMERICA, name: "Chile", code: "CL" },
  { continent: Continent.ASIA, name: "China", code: "CN" },
  { continent: Continent.ASIA, name: "Taiwan", code: "TW" },
  { continent: Continent.ASIA, name: "Christmas Island", code: "CX" },
  { continent: Continent.ASIA, name: "Cocos (Keeling) Islands", code: "CC" },
  { continent: Continent.S_AMERICA, name: "Colombia", code: "CO" },
  { continent: Continent.AFRICA, name: "Comoros the", code: "KM" },
  { continent: Continent.AFRICA, name: "Mayotte", code: "YT" },
  { continent: Continent.AFRICA, name: "Congo the", code: "CG" },
  { continent: Continent.AFRICA, name: "Congo", code: "CD" },
  { continent: Continent.OCEANIA, name: "Cook Islands", code: "CK" },
  { continent: Continent.N_AMERICA, name: "Costa Rica", code: "CR" },
  { continent: Continent.EUROPE, name: "Croatia", code: "HR" },
  { continent: Continent.N_AMERICA, name: "Cuba", code: "CU" },
  { continent: Continent.EUROPE, name: "Cyprus", code: "CY" },
  // { continent: Continent.ASIA, name: "Cyprus", code: "CY" },
  { continent: Continent.EUROPE, name: "Czech Republic", code: "CZ" },
  { continent: Continent.AFRICA, name: "Benin", code: "BJ" },
  { continent: Continent.EUROPE, name: "Denmark", code: "DK" },
  { continent: Continent.N_AMERICA, name: "Dominica", code: "DM" },
  { continent: Continent.N_AMERICA, name: "Dominican Republic", code: "DO" },
  { continent: Continent.S_AMERICA, name: "Ecuador", code: "EC" },
  { continent: Continent.N_AMERICA, name: "El Salvador", code: "SV" },
  { continent: Continent.AFRICA, name: "Equatorial Guinea", code: "GQ" },
  { continent: Continent.AFRICA, name: "Ethiopia", code: "ET" },
  { continent: Continent.AFRICA, name: "Eritrea", code: "ER" },
  { continent: Continent.EUROPE, name: "Estonia", code: "EE" },
  { continent: Continent.EUROPE, name: "Faroe Islands", code: "FO" },
  {
    continent: Continent.S_AMERICA,
    name: "Falkland Islands (Malvinas)",
    code: "FK",
  },
  {
    continent: Continent.ANTARCTICA,
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
  },
  {
    continent: Continent.OCEANIA,
    name: "Fiji the Fiji Islands",
    code: "FJ",
  },
  { continent: Continent.EUROPE, name: "Finland", code: "FI" },
  { continent: Continent.EUROPE, name: "Åland Islands", code: "AX" },
  { continent: Continent.EUROPE, name: "France", code: "FR" },
  { continent: Continent.S_AMERICA, name: "French Guiana", code: "GF" },
  { continent: Continent.OCEANIA, name: "French Polynesia", code: "PF" },
  {
    continent: Continent.ANTARCTICA,
    name: "French Southern Territories",
    code: "TF",
  },
  { continent: Continent.AFRICA, name: "Djibouti", code: "DJ" },
  { continent: Continent.AFRICA, name: "Gabon", code: "GA" },
  { continent: Continent.EUROPE, name: "Georgia", code: "GE" },
  // { continent: Continent.ASIA, name: "Georgia", code: "GE" },
  { continent: Continent.AFRICA, name: "Gambia the", code: "GM" },
  { continent: Continent.ASIA, name: "Palestinian Territory", code: "PS" },
  { continent: Continent.EUROPE, name: "Germany", code: "DE" },
  { continent: Continent.AFRICA, name: "Ghana", code: "GH" },
  { continent: Continent.EUROPE, name: "Gibraltar", code: "GI" },
  { continent: Continent.OCEANIA, name: "Kiribati", code: "KI" },
  { continent: Continent.EUROPE, name: "Greece", code: "GR" },
  { continent: Continent.N_AMERICA, name: "Greenland", code: "GL" },
  { continent: Continent.N_AMERICA, name: "Grenada", code: "GD" },
  { continent: Continent.N_AMERICA, name: "Guadeloupe", code: "GP" },
  { continent: Continent.OCEANIA, name: "Guam", code: "GU" },
  { continent: Continent.N_AMERICA, name: "Guatemala", code: "GT" },
  { continent: Continent.AFRICA, name: "Guinea", code: "GN" },
  { continent: Continent.S_AMERICA, name: "Guyana", code: "GY" },
  { continent: Continent.N_AMERICA, name: "Haiti", code: "HT" },
  {
    continent: Continent.ANTARCTICA,
    name: "Heard Island and McDonald Islands",
    code: "HM",
  },
  {
    continent: Continent.EUROPE,
    name: "Holy See (Vatican City State)",
    code: "VA",
  },
  { continent: Continent.N_AMERICA, name: "Honduras", code: "HN" },
  { continent: Continent.ASIA, name: "Hong Kong", code: "HK" },
  { continent: Continent.EUROPE, name: "Hungary", code: "HU" },
  { continent: Continent.EUROPE, name: "Iceland", code: "IS" },
  { continent: Continent.ASIA, name: "India", code: "IN" },
  { continent: Continent.ASIA, name: "Indonesia", code: "ID" },
  { continent: Continent.ASIA, name: "Iran", code: "IR" },
  { continent: Continent.ASIA, name: "Iraq", code: "IQ" },
  { continent: Continent.EUROPE, name: "Ireland", code: "IE" },
  { continent: Continent.ASIA, name: "Israel", code: "IL" },
  { continent: Continent.EUROPE, name: "Italy", code: "IT" },
  { continent: Continent.AFRICA, name: "Cote d'Ivoire", code: "CI" },
  { continent: Continent.N_AMERICA, name: "Jamaica", code: "JM" },
  { continent: Continent.ASIA, name: "Japan", code: "JP" },
  { continent: Continent.EUROPE, name: "Kazakhstan", code: "KZ" },
  // { continent: Continent.ASIA, name: "Kazakhstan", code: "KZ" },
  { continent: Continent.ASIA, name: "Jordan", code: "JO" },
  { continent: Continent.AFRICA, name: "Kenya", code: "KE" },
  { continent: Continent.ASIA, name: "Korea", code: "KP" },
  { continent: Continent.ASIA, name: "Korea", code: "KR" },
  { continent: Continent.ASIA, name: "Kuwait", code: "KW" },
  { continent: Continent.ASIA, name: "Kyrgyz Republic", code: "KG" },
  { continent: Continent.ASIA, name: "Lao", code: "LA" },
  { continent: Continent.ASIA, name: "Lebanon", code: "LB" },
  { continent: Continent.AFRICA, name: "Lesotho", code: "LS" },
  { continent: Continent.EUROPE, name: "Latvia", code: "LV" },
  { continent: Continent.AFRICA, name: "Liberia", code: "LR" },
  {
    continent: Continent.AFRICA,
    name: "Libyan Arab Jamahiriya",
    code: "LY",
  },
  { continent: Continent.EUROPE, name: "Liechtenstein", code: "LI" },
  { continent: Continent.EUROPE, name: "Lithuania", code: "LT" },
  { continent: Continent.EUROPE, name: "Luxembourg", code: "LU" },
  { continent: Continent.ASIA, name: "Macao", code: "MO" },
  { continent: Continent.AFRICA, name: "Madagascar", code: "MG" },
  { continent: Continent.AFRICA, name: "Malawi", code: "MW" },
  { continent: Continent.ASIA, name: "Malaysia", code: "MY" },
  { continent: Continent.ASIA, name: "Maldives", code: "MV" },
  { continent: Continent.AFRICA, name: "Mali", code: "ML" },
  { continent: Continent.EUROPE, name: "Malta", code: "MT" },
  { continent: Continent.N_AMERICA, name: "Martinique", code: "MQ" },
  { continent: Continent.AFRICA, name: "Mauritania", code: "MR" },
  { continent: Continent.AFRICA, name: "Mauritius", code: "MU" },
  { continent: Continent.N_AMERICA, name: "Mexico", code: "MX" },
  { continent: Continent.EUROPE, name: "Monaco", code: "MC" },
  { continent: Continent.ASIA, name: "Mongolia", code: "MN" },
  { continent: Continent.EUROPE, name: "Moldova", code: "MD" },
  { continent: Continent.EUROPE, name: "Montenegro", code: "ME" },
  { continent: Continent.N_AMERICA, name: "Montserrat", code: "MS" },
  { continent: Continent.AFRICA, name: "Morocco", code: "MA" },
  { continent: Continent.AFRICA, name: "Mozambique", code: "MZ" },
  { continent: Continent.ASIA, name: "Oman", code: "OM" },
  { continent: Continent.AFRICA, name: "Namibia", code: "NA" },
  { continent: Continent.OCEANIA, name: "Nauru", code: "NR" },
  { continent: Continent.ASIA, name: "Nepal", code: "NP" },
  { continent: Continent.EUROPE, name: "Netherlands the", code: "NL" },
  {
    continent: Continent.N_AMERICA,
    name: "Netherlands Antilles",
    code: "AN",
  },
  { continent: Continent.N_AMERICA, name: "Curaçao", code: "CW" },
  { continent: Continent.N_AMERICA, name: "Aruba", code: "AW" },
  {
    continent: Continent.N_AMERICA,
    name: "Sint Maarten (Netherlands)",
    code: "SX",
  },
  { continent: Continent.N_AMERICA, name: "Bonaire", code: "BQ" },
  { continent: Continent.OCEANIA, name: "New Caledonia", code: "NC" },
  { continent: Continent.OCEANIA, name: "Vanuatu", code: "VU" },
  { continent: Continent.OCEANIA, name: "New Zealand", code: "NZ" },
  { continent: Continent.N_AMERICA, name: "Nicaragua", code: "NI" },
  { continent: Continent.AFRICA, name: "Niger", code: "NE" },
  { continent: Continent.AFRICA, name: "Nigeria", code: "NG" },
  { continent: Continent.OCEANIA, name: "Niue", code: "NU" },
  { continent: Continent.OCEANIA, name: "Norfolk Island", code: "NF" },
  { continent: Continent.EUROPE, name: "Norway", code: "NO" },
  {
    continent: Continent.OCEANIA,
    name: "Northern Mariana Islands the",
    code: "MP",
  },
  // {
  //   continent: Continent.OCEANIA,
  //   name: "United States Minor Outlying Islands",
  //   code: "UM",
  // },
  {
    continent: Continent.N_AMERICA,
    name: "United States Minor Outlying Islands",
    code: "UM",
  },
  { continent: Continent.OCEANIA, name: "Micronesia", code: "FM" },
  { continent: Continent.OCEANIA, name: "Marshall Islands the", code: "MH" },
  { continent: Continent.OCEANIA, name: "Palau", code: "PW" },
  { continent: Continent.ASIA, name: "Pakistan", code: "PK" },
  { continent: Continent.N_AMERICA, name: "Panama", code: "PA" },
  { continent: Continent.OCEANIA, name: "Papua New Guinea", code: "PG" },
  { continent: Continent.S_AMERICA, name: "Paraguay", code: "PY" },
  { continent: Continent.S_AMERICA, name: "Peru", code: "PE" },
  { continent: Continent.ASIA, name: "Philippines the", code: "PH" },
  { continent: Continent.OCEANIA, name: "Pitcairn Islands", code: "PN" },
  { continent: Continent.EUROPE, name: "Poland", code: "PL" },
  { continent: Continent.EUROPE, name: "Portugal", code: "PT" },
  { continent: Continent.AFRICA, name: "Guinea-Bissau", code: "GW" },
  { continent: Continent.ASIA, name: "Timor-Leste", code: "TL" },
  { continent: Continent.N_AMERICA, name: "Puerto Rico", code: "PR" },
  { continent: Continent.ASIA, name: "Qatar", code: "QA" },
  { continent: Continent.AFRICA, name: "Reunion", code: "RE" },
  { continent: Continent.EUROPE, name: "Romania", code: "RO" },
  // { continent: Continent.EUROPE, name: "Russian Federation", code: "RU" },
  { continent: Continent.ASIA, name: "Russian Federation", code: "RU" },
  { continent: Continent.AFRICA, name: "Rwanda", code: "RW" },
  { continent: Continent.N_AMERICA, name: "Saint Barthelemy", code: "BL" },
  { continent: Continent.AFRICA, name: "Saint Helena", code: "SH" },
  {
    continent: Continent.N_AMERICA,
    name: "Saint Kitts and Nevis",
    code: "KN",
  },
  { continent: Continent.N_AMERICA, name: "Anguilla", code: "AI" },
  { continent: Continent.N_AMERICA, name: "Saint Lucia", code: "LC" },
  { continent: Continent.N_AMERICA, name: "Saint Martin", code: "MF" },
  {
    continent: Continent.N_AMERICA,
    name: "Saint Pierre and Miquelon",
    code: "PM",
  },
  {
    continent: Continent.N_AMERICA,
    name: "Saint Vincent and the Grenadines",
    code: "VC",
  },
  { continent: Continent.EUROPE, name: "San Marino", code: "SM" },
  { continent: Continent.AFRICA, name: "Sao Tome and Principe", code: "ST" },
  { continent: Continent.ASIA, name: "Saudi Arabia", code: "SA" },
  { continent: Continent.AFRICA, name: "Senegal", code: "SN" },
  { continent: Continent.EUROPE, name: "Serbia", code: "RS" },
  { continent: Continent.AFRICA, name: "Seychelles", code: "SC" },
  { continent: Continent.AFRICA, name: "Sierra Leone", code: "SL" },
  { continent: Continent.ASIA, name: "Singapore", code: "SG" },
  { continent: Continent.EUROPE, name: "Slovakia", code: "SK" },
  { continent: Continent.ASIA, name: "Vietnam", code: "VN" },
  { continent: Continent.EUROPE, name: "Slovenia", code: "SI" },
  { continent: Continent.AFRICA, name: "Somalia", code: "SO" },
  { continent: Continent.AFRICA, name: "South Africa", code: "ZA" },
  { continent: Continent.AFRICA, name: "Zimbabwe", code: "ZW" },
  { continent: Continent.EUROPE, name: "Spain", code: "ES" },
  { continent: Continent.AFRICA, name: "South Sudan", code: "SS" },
  { continent: Continent.AFRICA, name: "Western Sahara", code: "EH" },
  { continent: Continent.AFRICA, name: "Sudan", code: "SD" },
  { continent: Continent.S_AMERICA, name: "Suriname", code: "SR" },
  {
    continent: Continent.EUROPE,
    name: "Svalbard & Jan Mayen Islands",
    code: "SJ",
  },
  { continent: Continent.AFRICA, name: "Swaziland", code: "SZ" },
  { continent: Continent.EUROPE, name: "Sweden", code: "SE" },
  { continent: Continent.EUROPE, name: "Switzerland", code: "CH" },
  { continent: Continent.ASIA, name: "Syrian Arab Republic", code: "SY" },
  { continent: Continent.ASIA, name: "Tajikistan", code: "TJ" },
  { continent: Continent.ASIA, name: "Thailand", code: "TH" },
  { continent: Continent.AFRICA, name: "Togo", code: "TG" },
  { continent: Continent.OCEANIA, name: "Tokelau", code: "TK" },
  { continent: Continent.OCEANIA, name: "Tonga", code: "TO" },
  {
    continent: Continent.N_AMERICA,
    name: "Trinidad and Tobago",
    code: "TT",
  },
  { continent: Continent.ASIA, name: "United Arab Emirates", code: "AE" },
  { continent: Continent.AFRICA, name: "Tunisia", code: "TN" },
  { continent: Continent.EUROPE, name: "Turkey", code: "TR" },
  // { continent: Continent.ASIA, name: "Turkey", code: "TR" },
  { continent: Continent.ASIA, name: "Turkmenistan", code: "TM" },
  {
    continent: Continent.N_AMERICA,
    name: "Turks and Caicos Islands",
    code: "TC",
  },
  { continent: Continent.OCEANIA, name: "Tuvalu", code: "TV" },
  { continent: Continent.AFRICA, name: "Uganda", code: "UG" },
  { continent: Continent.EUROPE, name: "Ukraine", code: "UA" },
  { continent: Continent.EUROPE, name: "Macedonia", code: "MK" },
  { continent: Continent.AFRICA, name: "Egypt", code: "EG" },
  {
    continent: Continent.EUROPE,
    name: "United Kingdom of Great Britain & Northern Ireland",
    code: "GB",
  },
  { continent: Continent.EUROPE, name: "Guernsey", code: "GG" },
  { continent: Continent.EUROPE, name: "Jersey", code: "JE" },
  { continent: Continent.EUROPE, name: "Isle of Man", code: "IM" },
  { continent: Continent.AFRICA, name: "Tanzania", code: "TZ" },
  {
    continent: Continent.N_AMERICA,
    name: "United States of America",
    code: "US",
  },
  {
    continent: Continent.N_AMERICA,
    name: "United States Virgin Islands",
    code: "VI",
  },
  { continent: Continent.AFRICA, name: "Burkina Faso", code: "BF" },
  { continent: Continent.S_AMERICA, name: "Uruguay", code: "UY" },
  { continent: Continent.ASIA, name: "Uzbekistan", code: "UZ" },
  { continent: Continent.S_AMERICA, name: "Venezuela", code: "VE" },
  { continent: Continent.OCEANIA, name: "Wallis and Futuna", code: "WF" },
  { continent: Continent.OCEANIA, name: "Samoa", code: "WS" },
  { continent: Continent.ASIA, name: "Yemen", code: "YE" },
  { continent: Continent.AFRICA, name: "Zambia", code: "ZM" },
  { continent: Continent.OCEANIA, name: "Disputed Territory", code: "XX" },
  {
    continent: Continent.ASIA,
    name: "Iraq-Saudi Arabia Neutral Zone",
    code: "XE",
  },
  {
    continent: Continent.ASIA,
    name: "United Nations Neutral Zone",
    code: "XD",
  },
  { continent: Continent.ASIA, name: "Spratly Islands", code: "XS" },
].sort((a, b) => a.name.localeCompare(b.name));
